/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MainController;

import java.awt.ComponentOrientation;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author youssefali
 */
public class MainWindow extends javax.swing.JFrame {
    
    MainController controller;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        controller = new MainController();
        jTable1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        expressionAddText = new javax.swing.JTextArea();
        addExpressionBtn = new javax.swing.JButton();
        expressionNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        expressionNumberTT = new javax.swing.JTextField();
        getTTBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        saveTTBtn = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        eqivExpr1 = new javax.swing.JTextField();
        getEquivBtn = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        ShowEquiv = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        eqivExpr2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        contraExpr = new javax.swing.JTextField();
        contraCheck = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        showContra = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tautExpr = new javax.swing.JTextField();
        tautCheck = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        showTaut = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        expressionNumberShow = new javax.swing.JTextField();
        showSetBnt = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        showExpressionText = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(144, 193, 241));

        jLabel1.setBackground(new java.awt.Color(144, 193, 241));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(18, 82, 216));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Truth Table Generator");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N

        jTabbedPane1.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Add a new expression");

        expressionAddText.setColumns(20);
        expressionAddText.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        expressionAddText.setRows(5);
        expressionAddText.setWrapStyleWord(true);
        expressionAddText.setName(""); // NOI18N
        jScrollPane3.setViewportView(expressionAddText);

        addExpressionBtn.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        addExpressionBtn.setText("Add Expression");
        addExpressionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpressionBtnActionPerformed(evt);
            }
        });

        expressionNumber.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        jLabel3.setText("Expression number:");

        jLayeredPane2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(addExpressionBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(expressionNumber, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 969, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addExpressionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(expressionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expressionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addExpressionBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Expressions", jLayeredPane2);

        jTabbedPane2.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        jLabel7.setText("Expression number:");

        expressionNumberTT.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N

        getTTBtn.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        getTTBtn.setText("Generate");
        getTTBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTTBtnActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setEnabled(false);
        jTable1.setName("Truth Table"); // NOI18N
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        saveTTBtn.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        saveTTBtn.setText("Save As Text File");
        saveTTBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTTBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(expressionNumberTT, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(getTTBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                        .addGap(11, 11, 11)
                        .addComponent(saveTTBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expressionNumberTT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(getTTBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveTTBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Get Truth Table", jPanel2);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        jLabel13.setText("First expression number:");

        eqivExpr1.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N

        getEquivBtn.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        getEquivBtn.setText("Check");
        getEquivBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getEquivBtnActionPerformed(evt);
            }
        });

        ShowEquiv.setColumns(20);
        ShowEquiv.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        ShowEquiv.setRows(5);
        ShowEquiv.setText("Test result will be shown here.");
        ShowEquiv.setWrapStyleWord(true);
        jScrollPane6.setViewportView(ShowEquiv);

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        jLabel14.setText("Second expression number:");

        eqivExpr2.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(4, 4, 4)
                        .addComponent(eqivExpr1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(4, 4, 4)
                        .addComponent(eqivExpr2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getEquivBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eqivExpr2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eqivExpr1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(getEquivBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Equivalence Test", jPanel5);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        jLabel11.setText("Expression number:");

        contraExpr.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N

        contraCheck.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        contraCheck.setText("Check");
        contraCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraCheckActionPerformed(evt);
            }
        });

        showContra.setColumns(20);
        showContra.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        showContra.setRows(5);
        showContra.setText("Test result will be shown here.");
        showContra.setWrapStyleWord(true);
        jScrollPane5.setViewportView(showContra);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(4, 4, 4)
                        .addComponent(contraExpr, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(340, 340, 340)
                        .addComponent(contraCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contraExpr, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(contraCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Contradiction Test", jPanel4);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        jLabel9.setText("Expression number:");

        tautExpr.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N

        tautCheck.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        tautCheck.setText("Check");
        tautCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tautCheckActionPerformed(evt);
            }
        });

        showTaut.setColumns(20);
        showTaut.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        showTaut.setRows(5);
        showTaut.setText("Test result will be shown here.");
        showTaut.setWrapStyleWord(true);
        jScrollPane4.setViewportView(showTaut);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addComponent(tautExpr, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(340, 340, 340)
                        .addComponent(tautCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tautExpr, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tautCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Tautology Test", jPanel3);

        jTabbedPane2.addTab("Tests", jTabbedPane3);

        expressionNumberShow.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N

        showSetBnt.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        showSetBnt.setText("Show expression");
        showSetBnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSetBntActionPerformed(evt);
            }
        });

        showExpressionText.setColumns(20);
        showExpressionText.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        showExpressionText.setRows(5);
        showExpressionText.setText("Expression will be shown here");
        showExpressionText.setWrapStyleWord(true);
        jScrollPane11.setViewportView(showExpressionText);

        jLabel21.setFont(new java.awt.Font("Ubuntu", 0, 23)); // NOI18N
        jLabel21.setText("Expression number:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(4, 4, 4)
                        .addComponent(expressionNumberShow, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267)
                        .addComponent(showSetBnt, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expressionNumberShow, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showSetBnt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Show Expression", jPanel11);

        jLayeredPane3.setLayer(jTabbedPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Get Truth Table");

        jTabbedPane1.addTab("Operations", jLayeredPane3);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 21)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Made by: Youssef Ali & Mostafa Labib, 2017");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getEquivBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getEquivBtnActionPerformed
        if(eqivExpr1.getText().equals("") || eqivExpr2.getText().equals(""))
            return;
        String testEquivResult = controller.testEquiv(Integer.parseInt(eqivExpr1.getText()), Integer.parseInt(eqivExpr2.getText()));
        ShowEquiv.setText(testEquivResult);
    }//GEN-LAST:event_getEquivBtnActionPerformed

    private void contraCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraCheckActionPerformed
        if(contraExpr.getText().equals(""))
            return;
        String testContradictionResult = controller.testContradiction(Integer.parseInt(contraExpr.getText()));
        showContra.setText(testContradictionResult);
    }//GEN-LAST:event_contraCheckActionPerformed

    private void tautCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tautCheckActionPerformed
        if(tautExpr.getText().equals(""))
            return;
        String testTautologyResult = controller.testTautology(Integer.parseInt(tautExpr.getText()));
        showTaut.setText(testTautologyResult);
    }//GEN-LAST:event_tautCheckActionPerformed

    private void getTTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTTBtnActionPerformed
        if(expressionNumberTT.getText().equals(""))
            return;
        String[][] truthTable = controller.getTruthTable(Integer.parseInt(expressionNumberTT.getText()));
        //Boolean[][] truthTable = controller.getExpressionAt(Integer.parseInt(expressionNumberTT.getText())).getTruthTable();
        //Character[] symbols = controller.getExpressionAt(Integer.parseInt(expressionNumberTT.getText())).getSymbols();
        String[] titles = controller.getTitles(Integer.parseInt(expressionNumberTT.getText()));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(truthTable, titles));
        jTable1.setVisible(true);
    }//GEN-LAST:event_getTTBtnActionPerformed

    private void addExpressionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpressionBtnActionPerformed
        if(expressionNumber.getText().equals(""))
            return;
        int enteredExpresionNumber = Integer.parseInt(expressionNumber.getText());
        String expr = expressionAddText.getText().replaceAll(" ", "");
        
        controller.addExpressionAt(expr, enteredExpresionNumber);
        
    }//GEN-LAST:event_addExpressionBtnActionPerformed

    private void showSetBntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSetBntActionPerformed
        if(expressionNumberShow.getText().equals(""))
            return;
        String text = controller.getExpressionAt(Integer.parseInt(expressionNumberShow.getText())).getExpression();
        showExpressionText.setText(text);
    }//GEN-LAST:event_showSetBntActionPerformed

    private void saveTTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTTBtnActionPerformed
        if(expressionNumberTT.getText().equals(""))
            return;
        JFileChooser saveFileChooser = new JFileChooser();
        saveFileChooser.setSelectedFile(new File("truthTable"));
        saveFileChooser.setAcceptAllFileFilterUsed(false);
        saveFileChooser.addChoosableFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if(f.isDirectory())
                    return true;
                if(f.getName().endsWith(".txt"))
                    return true;
                return false;
            }

            @Override
            public String getDescription() {
                return ".txt";
            }
        });
        int ret = saveFileChooser.showSaveDialog(jPanel1);
        if(ret == JFileChooser.APPROVE_OPTION){
            File file = new File(saveFileChooser.getCurrentDirectory().getPath() + File.separator
                               + saveFileChooser.getSelectedFile().getName()
                               + saveFileChooser.getFileFilter().getDescription());
            controller.saveTruthTable(file, Integer.parseInt(expressionNumberTT.getText()));
        }
    }//GEN-LAST:event_saveTTBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ShowEquiv;
    private javax.swing.JButton addExpressionBtn;
    private javax.swing.JButton contraCheck;
    private javax.swing.JTextField contraExpr;
    private javax.swing.JTextField eqivExpr1;
    private javax.swing.JTextField eqivExpr2;
    private javax.swing.JTextArea expressionAddText;
    private javax.swing.JTextField expressionNumber;
    private javax.swing.JTextField expressionNumberShow;
    private javax.swing.JTextField expressionNumberTT;
    private javax.swing.JButton getEquivBtn;
    private javax.swing.JButton getTTBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton saveTTBtn;
    private javax.swing.JTextArea showContra;
    private javax.swing.JTextArea showExpressionText;
    private javax.swing.JButton showSetBnt;
    private javax.swing.JTextArea showTaut;
    private javax.swing.JButton tautCheck;
    private javax.swing.JTextField tautExpr;
    // End of variables declaration//GEN-END:variables
}
